// <autogenerated>
//   Do not modify this file manually. Any changes will be lost next time the code is regenerated.
// </autogenerated>

namespace T4WebFormsInjection.App.Handlers
{
    using System;

    public partial class Handler1
    {
        [Obsolete("Use T4WebFormsInjection.App.Handlers.T4WebFormsInjection.App.Handlers(dummyInterface) instead.")]
        public Handler1()
            : this(dummyInterface: T4WebFormsInjection.App.Code.Container.GetInstance<T4WebFormsInjection.App.Code.IDummyInterface>())
        {
        }
    }

    public partial class Handler2
    {
        [Obsolete("Use T4WebFormsInjection.App.Handlers.T4WebFormsInjection.App.Handlers(dummyInterface, dummyInterface2) instead.")]
        public Handler2()
            : this(dummyInterface: T4WebFormsInjection.App.Code.Container.GetInstance<T4WebFormsInjection.App.Code.IDummyInterface>(),
                   dummyInterface2: T4WebFormsInjection.App.Code.Container.GetInstance<T4WebFormsInjection.App.Code.IDummyInterface2>())
        {
        }
    }
}

namespace T4WebFormsInjection.App.Modules
{
    using System;

    public partial class MyModule1
    {
        [Obsolete("Use T4WebFormsInjection.App.Modules.T4WebFormsInjection.App.Modules(dummyInterface) instead.")]
        public MyModule1()
            : this(dummyInterface: T4WebFormsInjection.App.Code.Container.GetInstance<T4WebFormsInjection.App.Code.IDummyInterface>())
        {
        }
    }

    public partial class MyModule2
    {
        [Obsolete("Use T4WebFormsInjection.App.Modules.T4WebFormsInjection.App.Modules(dummyInterface, dummyInterface2) instead.")]
        public MyModule2()
            : this(dummyInterface: T4WebFormsInjection.App.Code.Container.GetInstance<T4WebFormsInjection.App.Code.IDummyInterface>(),
                   dummyInterface2: T4WebFormsInjection.App.Code.Container.GetInstance<T4WebFormsInjection.App.Code.IDummyInterface2>())
        {
        }
    }
}

namespace T4WebFormsInjection.App.Pages
{
    using System;

    public partial class WebForm1
    {
        [Obsolete("Use T4WebFormsInjection.App.Pages.T4WebFormsInjection.App.Pages(dummyInterface, dummyInterfaceFromPartial) instead.")]
        public WebForm1()
            : this(dummyInterface: T4WebFormsInjection.App.Code.Container.GetInstance<T4WebFormsInjection.App.Code.IDummyInterface>(),
                   dummyInterfaceFromPartial: T4WebFormsInjection.App.Code.Container.GetInstance<T4WebFormsInjection.App.Code.IDummyInterface>())
        {
        }
    }

    public partial class WebForm2
    {
        [Obsolete("Use T4WebFormsInjection.App.Pages.T4WebFormsInjection.App.Pages(dummyInterface, dummyInterface2) instead.")]
        public WebForm2()
            : this(dummyInterface: T4WebFormsInjection.App.Code.Container.GetInstance<T4WebFormsInjection.App.Code.IDummyInterface>(),
                   dummyInterface2: T4WebFormsInjection.App.Code.Container.GetInstance<T4WebFormsInjection.App.Code.IDummyInterface2>())
        {
        }
    }
}

namespace T4WebFormsInjection.App.UserControls
{
    using System;

    public partial class UC1
    {
        [Obsolete("Use T4WebFormsInjection.App.UserControls.T4WebFormsInjection.App.UserControls(dummyInterface) instead.")]
        public UC1()
            : this(dummyInterface: T4WebFormsInjection.App.Code.Container.GetInstance<T4WebFormsInjection.App.Code.IDummyInterface>())
        {
        }
    }

    public partial class UC2
    {
        [Obsolete("Use T4WebFormsInjection.App.UserControls.T4WebFormsInjection.App.UserControls(dummyInterface, dummyInterface2) instead.")]
        public UC2()
            : this(dummyInterface: T4WebFormsInjection.App.Code.Container.GetInstance<T4WebFormsInjection.App.Code.IDummyInterface>(),
                   dummyInterface2: T4WebFormsInjection.App.Code.Container.GetInstance<T4WebFormsInjection.App.Code.IDummyInterface2>())
        {
        }
    }
}


