// <autogenerated>
//   Do not modify this file manually. Any changes will be lost next time the code is regenerated.
// </autogenerated>

namespace T4WebFormsInjection.App.MasterPages
{
    using System;

    public partial class Site1
    {
        [Obsolete("Use T4WebFormsInjection.App.MasterPages.T4WebFormsInjection.App.MasterPages(dummyInterface) instead.")]
        public Site1()
            : this(dummyInterface: T4WebFormsInjection.App.Code.Container.GetInstance<T4WebFormsInjection.App.Code.IDummyInterface>())
        {
        }
    }
}

namespace T4WebFormsInjection.App.Pages
{
    using System;

    public partial class WebForm1
    {
        [Obsolete("Use T4WebFormsInjection.App.Pages.T4WebFormsInjection.App.Pages(dummyInterface, dummyInterfaceFromPartial) instead.")]
        public WebForm1()
            : this(dummyInterface: T4WebFormsInjection.App.Code.Container.GetInstance<T4WebFormsInjection.App.Code.IDummyInterface>(),
                   dummyInterfaceFromPartial: T4WebFormsInjection.App.Code.Container.GetInstance<T4WebFormsInjection.App.Code.IDummyInterface>())
        {
        }
    }

    public partial class WebForm2
    {
        [Obsolete("Use T4WebFormsInjection.App.Pages.T4WebFormsInjection.App.Pages(dummyInterface, dummyInterface2) instead.")]
        public WebForm2()
            : this(dummyInterface: T4WebFormsInjection.App.Code.Container.GetInstance<T4WebFormsInjection.App.Code.IDummyInterface>(),
                   dummyInterface2: T4WebFormsInjection.App.Code.Container.GetInstance<T4WebFormsInjection.App.Code.IDummyInterface2>())
        {
        }
    }
}

namespace T4WebFormsInjection.App.UserControls
{
    using System;

    public partial class UC1
    {
        [Obsolete("Use T4WebFormsInjection.App.UserControls.T4WebFormsInjection.App.UserControls(dummyInterface) instead.")]
        public UC1()
            : this(dummyInterface: T4WebFormsInjection.App.Code.Container.GetInstance<T4WebFormsInjection.App.Code.IDummyInterface>())
        {
        }
    }

    public partial class UC2
    {
        [Obsolete("Use T4WebFormsInjection.App.UserControls.T4WebFormsInjection.App.UserControls(dummyInterface, dummyInterface2) instead.")]
        public UC2()
            : this(dummyInterface: T4WebFormsInjection.App.Code.Container.GetInstance<T4WebFormsInjection.App.Code.IDummyInterface>(),
                   dummyInterface2: T4WebFormsInjection.App.Code.Container.GetInstance<T4WebFormsInjection.App.Code.IDummyInterface2>())
        {
        }
    }
}


