// <autogenerated>
//   Do not modify this file manually. Any changes will be lost next time the code is regenerated.
// </autogenerated>

namespace T4WFI.App
{
	using System;
	using System.Collections.Generic;

	public static class T4WebFormsInjection
	{
		public static IEnumerable<Type> RegisteredTypes
		{
			get
			{
				yield return typeof(T4WFI.App.Code.IDummyInterface);
				yield return typeof(T4WFI.App.Code.IDummyInterface2);
			}
		}
	}
}

namespace T4WFI.App.Handlers
{
    using System;

    public partial class Handler1
    {
        [Obsolete("Use T4WFI.App.Handlers.Handler1(dummyInterface) instead.")]
        public Handler1()
            : this(dummyInterface: T4WFI.App.Code.Container.GetInstance<T4WFI.App.Code.IDummyInterface>())
        {
        }
    }

    public partial class Handler2
    {
        [Obsolete("Use T4WFI.App.Handlers.Handler2(dummyInterface, dummyInterface2) instead.")]
        public Handler2()
            : this(dummyInterface: T4WFI.App.Code.Container.GetInstance<T4WFI.App.Code.IDummyInterface>(),
                   dummyInterface2: T4WFI.App.Code.Container.GetInstance<T4WFI.App.Code.IDummyInterface2>())
        {
        }
    }
}

namespace T4WFI.App.MasterPages
{
    using System;

    public partial class Site1
    {
        [Obsolete("Use T4WFI.App.MasterPages.Site1(dummyInterface) instead.")]
        public Site1()
            : this(dummyInterface: T4WFI.App.Code.Container.GetInstance<T4WFI.App.Code.IDummyInterface>())
        {
        }
    }
}

namespace T4WFI.App.Modules
{
    using System;

    public partial class MyModule1
    {
        [Obsolete("Use T4WFI.App.Modules.MyModule1(dummyInterface) instead.")]
        public MyModule1()
            : this(dummyInterface: T4WFI.App.Code.Container.GetInstance<T4WFI.App.Code.IDummyInterface>())
        {
        }
    }

    public partial class MyModule2
    {
        [Obsolete("Use T4WFI.App.Modules.MyModule2(dummyInterface, dummyInterface2) instead.")]
        public MyModule2()
            : this(dummyInterface: T4WFI.App.Code.Container.GetInstance<T4WFI.App.Code.IDummyInterface>(),
                   dummyInterface2: T4WFI.App.Code.Container.GetInstance<T4WFI.App.Code.IDummyInterface2>())
        {
        }
    }
}

namespace T4WFI.App.Pages
{
    using System;

    public partial class WebForm1
    {
        [Obsolete("Use T4WFI.App.Pages.WebForm1(dummyInterface, dummyInterfaceFromPartial) instead.")]
        public WebForm1()
            : this(dummyInterface: T4WFI.App.Code.Container.GetInstance<T4WFI.App.Code.IDummyInterface>(),
                   dummyInterfaceFromPartial: T4WFI.App.Code.Container.GetInstance<T4WFI.App.Code.IDummyInterface2>())
        {
        }
    }

    public partial class WebForm2
    {
        [Obsolete("Use T4WFI.App.Pages.WebForm2(dummyInterface, dummyInterface2) instead.")]
        public WebForm2()
            : this(dummyInterface: T4WFI.App.Code.Container.GetInstance<T4WFI.App.Code.IDummyInterface>(),
                   dummyInterface2: T4WFI.App.Code.Container.GetInstance<T4WFI.App.Code.IDummyInterface2>())
        {
        }
    }
}

namespace T4WFI.App.UserControls
{
    using System;

    public partial class UC1
    {
        [Obsolete("Use T4WFI.App.UserControls.UC1(dummyInterface) instead.")]
        public UC1()
            : this(dummyInterface: T4WFI.App.Code.Container.GetInstance<T4WFI.App.Code.IDummyInterface>())
        {
        }
    }

    public partial class UC2
    {
        [Obsolete("Use T4WFI.App.UserControls.UC2(dummyInterface, dummyInterface2) instead.")]
        public UC2()
            : this(dummyInterface: T4WFI.App.Code.Container.GetInstance<T4WFI.App.Code.IDummyInterface>(),
                   dummyInterface2: T4WFI.App.Code.Container.GetInstance<T4WFI.App.Code.IDummyInterface2>())
        {
        }
    }
}

namespace T4WFI.App.WebServices
{
    using System;

    public partial class WebService1
    {
        [Obsolete("Use T4WFI.App.WebServices.WebService1(dummyInterface, dummyInterface2) instead.")]
        public WebService1()
            : this(dummyInterface: T4WFI.App.Code.Container.GetInstance<T4WFI.App.Code.IDummyInterface>(),
                   dummyInterface2: T4WFI.App.Code.Container.GetInstance<T4WFI.App.Code.IDummyInterface2>())
        {
        }
    }
}

